# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

TensorBoardPort: 8888
TensorIPythonPort: 6006

commandline:
  args:
    - "/app/training.py"
    - "--data_dir=/temp"

image:
  pullPolicy: IfNotPresent
  clusterRepository: ''

service:
  type: ClusterIP

worker_resources:
  requests:
    cpu: 76
    memory: 240Gi
  limits:
    cpu: 76
    memory: 240Gi

ps_resources:
  requests:
    cpu: 76
    memory: 240Gi
  limits:
    cpu: 76
    memory: 240Gi

sidecar_resources:
  requests:
    cpu: 0.01
    memory: 1Gi


experimentName: ''

workersCount: 3
psSidecarLoggingLevel: "WARNING"
pServersCount: 1