kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-flannel-crb
  labels:
    app: {{ .Release.Name }}-flannel
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-flannel
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-flannel
  namespace: {{ .Release.Namespace }}
