kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-flannel
  labels:
    app: {{ .Release.Name }}-flannel
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "{{ required "POD network range is required" .Values.PodNetwork }}",
      "Backend": {
        "Type": "vxlan"
      }
    }
