required = ["sigs.k8s.io/testing_frameworks/integration",
            "k8s.io/client-go/plugin/pkg/client/auth",
            "github.com/spf13/pflag",
            "github.com/emicklei/go-restful",
            "github.com/go-openapi/spec",
            "k8s.io/kube-openapi/pkg/common",

            "k8s.io/code-generator/cmd/defaulter-gen",
            "k8s.io/code-generator/cmd/deepcopy-gen",
            "k8s.io/code-generator/cmd/conversion-gen",
            "k8s.io/code-generator/cmd/client-gen",
            "k8s.io/code-generator/cmd/lister-gen",
            "k8s.io/code-generator/cmd/informer-gen",
            "k8s.io/code-generator/cmd/openapi-gen",
           ]

[[constraint]]
  branch = "master"
  name = "github.com/markbates/inflect"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.1"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
    unused-packages = false
