---

registry_images:
  - name: "core/flannel:v0.9.1"
    src: "quay.io/coreos/flannel:v0.9.1-amd64"
  - name: "core/kube-proxy:v1.10.0"
    src: "gcr.io/google-containers/kube-proxy-amd64:v1.10.0"
  - name: "core/pause:3.1"
    src: "gcr.io/google-containers/pause-amd64:3.1"
  - name: "core/tiller:v2.8.1"
    src: "gcr.io/kubernetes-helm/tiller:v2.8.1"
  - name: "core/addon-resizer:1.7"
    src: "k8s.gcr.io/addon-resizer:1.7"
  - name: "core/heapster:v1.4.2"
    src: "k8s.gcr.io/heapster-amd64:v1.4.2"
  - name: "core/defaultbackend:1.4"
    src: "gcr.io/google-containers/defaultbackend-amd64:1.4"
  - name: "core/ingress:0.11.0"
    src: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.11.0"
  - name: "core/kube-dns:1.14.8"
    src: "gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.8"
  - name: "core/dnsmasq-nanny:1.14.8"
    src: "gcr.io/google-containers/k8s-dns-dnsmasq-nanny-amd64:1.14.8"
  - name: "core/dns-sidecar:1.14.8"
    src: "gcr.io/google-containers/k8s-dns-sidecar-amd64:1.14.8"
  - name: "core/etcd:3.1.10"
    src: "gcr.io/google-containers/etcd-amd64:3.1.10"
  - name: "core/nfs-provisioner:v1.0.8"
    src: "quay.io/kubernetes_incubator/nfs-provisioner:v1.0.8"
  - name: "core/dashboard:v1.8.3"
    src: "k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3"
