---

kubernetes_default_admission_control:
  - NamespaceLifecycle
  - NamespaceExists
  - ServiceAccount
  - LimitRanger
  - ResourceQuota
  - DefaultStorageClass

kubernetes_default_feature_gates: {}

kubernetes_default_runtime_config: {}

kubernetes_calculated_admission_control: "{{ (kubernetes_default_admission_control + kubernetes_admission_control | default([])) | unique }}"
kubernetes_calculated_feature_gates: "{{ (kubernetes_default_feature_gates | combine(kubernetes_feature_gates | default({}))) }}"
kubernetes_calculated_runtime_config: "{{ (kubernetes_default_runtime_config | combine(kubernetes_runtime_config | default({}))) }}"

kubernetes_anonymous_access: True
