---

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"

- name: Load MDM ips facts
  set_fact:
    SCALEIO_MDM_IPS: "{{ ((ansible_local.scaleio | default({}))['cluster'] | default({})).ips }}"

- name: Join all sdc in cluster
  include_tasks: join.yml
  with_items: "{{ groups['kubernetes-all'] }}"
  loop_control:
    loop_var: host
  when: hostvars[host].scaleio_sdc | default(True) | bool
