apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fluentd-config
  labels:
    app: {{ .Release.Name }}-fluentd
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data:
{{ (.Files.Glob "config/fluent.conf").AsConfig  | indent 2 }}
