---

- include_tasks: include_distribution.yml
  vars:
    distribution_file: install.yml

- name: Ensure registry directory exists
  file:
    path: /opt/dls4e/registry

- name: Replace configuration
  template:
    src: registry.yml.j2
    dest: /etc/docker-distribution/registry/config.yml
  notify:
    - Restart Docker Distribution

- meta: flush_handlers

- name: Start and enable docker distribution
  service:
    name: docker-distribution
    state: started
    enabled: True
