---

verification_checks:
  - message: "Can not find local_data_device under {{ local_data_device | default('') }} on host."
    condition: "{{ local_data_device is defined and local_data_device not in ansible_devices }}"
  - message: "Param dns_search_domains should be provided as list"
    condition: "{{ dns_search_domains is defined and dns_search_domains is string }}"
  - message: "Param dns_search_domains should be provided as list"
    condition: "{{ dns_search_domains is defined and dns_search_domains is string }}"
  - message: "Param insecure_registries should be provided as list"
    condition: "{{ dns_search_domains is defined and dns_search_domains is string }}"
  - message: "Param enabled_plugins should be provided as list"
    condition: "{{ enabled_plugins is defined and enabled_plugins is string }}"
  - message: "Param disabled_plugins should be provided as list"
    condition: "{{ disabled_plugins is defined and disabled_plugins is string }}"
  - message: "Param enabled_repos should be provided as list"
    condition: "{{ enabled_repos is defined and enabled_repos is string }}"
  - message: "Param disabled_repos should be provided as list"
    condition: "{{ disabled_repos is defined and disabled_repos is string }}"
  - message: "Param features should be provided as list"
    condition: "{{ features is defined and features is string }}"
  - message: "Param storage_type should be set to auto"
    condition: "{{ storage_type is defined and storage_type != 'auto' }}"
  - message: "Improper domain set in parameter {{ domain }}"
    condition: "{{ domain | regex_search ('^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]$') }}"
  - message: "Improper nodes_domain set in parameter {{ nodes_domain }}"
    condition: "{{ nodes_domain | regex_search ('^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]$') }}"
  - message: "Improper k8s_domain set in parameter {{ k8s_domain }}"
    condition: "{{ k8s_domain | regex_search ('^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]$') }}"
  - message: "Unable to parse kubernetes_pod_subnet as subnet from value {{ kubernetes_pod_subnet }}"
    condition: "{{ not kubernetes_pod_subnet | ipaddr }}"
  - message: "Unable to parse kubernetes_svc_subnet as subnet from value {{ kubernetes_svc_subnet }}"
    condition: "{{ not kubernetes_svc_subnet | ipaddr }}"
  - message: "Subnet for kubernetes_pod_subnet should be more than or equal 16"
    condition: "{{ kubernetes_pod_subnet | ipaddr('prefix') | int < 16 }}"
  - message: "Subnet for kubernetes_svc_subnet should be more than or equal 16"
    condition: "{{ kubernetes_svc_subnet | ipaddr('prefix') | int < 16 }}"
  - message: "Subnet for kubernetes_pod_subnet and kubernetes_svc_subnet can not be equal"
    condition: "{{ kubernetes_pod_subnet == kubernetes_svc_subnet }}"

required_parameters: []
