---

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"

- name: Load host facts
  set_fact:
    SCALEIO_MDM_FACTS: "{{ (ansible_local.scaleio | default({}))[CURRENT_MDM] | default({}) }}"

- name: Set {{ CURRENT_MDM }} node fact
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  ini_file:
    path: /etc/dls-facts/scaleio.fact
    section: "{{ CURRENT_MDM }}"
    option: "{{ item.name }}"
    no_extra_spaces: True
    value: "{{ item.value }}"
    mode: 0640
    owner: cluster-facts
    group: cluster-facts
  when: item.name not in SCALEIO_MDM_FACTS
  with_items:
    - name: ip
      value: "{{ hostvars[host].dls_configuration.data_interface.ipv4_address }}"
    - name: name
      value: "{{ hostvars[host].dls_configuration.network.instance_name }}"

- include: synchronize-facts.yml

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"

- name: Load host facts
  set_fact:
    SCALEIO_MDM_FACTS: "{{ (ansible_local.scaleio | default({}))[CURRENT_MDM] | default({}) }}"

- name: Fail if ip does not match
  fail:
    msg: "Ip for {{ CURRENT_MDM }}: expected {{ SCALEIO_MDM_FACTS.ip }} - got {{ hostvars[host].dls_configuration.data_interface.ipv4_address }}"
  when: SCALEIO_MDM_FACTS.ip != hostvars[host].dls_configuration.data_interface.ipv4_address

- name: Fail if name does not match
  fail:
    msg: "Ip for {{ CURRENT_MDM }}: expected {{ SCALEIO_MDM_FACTS.name }} - got {{ hostvars[host].dls_configuration.network.instance_name }}"
  when: SCALEIO_MDM_FACTS.name != hostvars[host].dls_configuration.network.instance_name

- name: Join mdm if did not join
  environment:
    SCLI_MDM: "{{ SCALEIO_MDM_0_FACTS.ip }}"
    SCLI_USERNAME: admin
    SCLI_PASSWORD: "{{ scaleio_password }}"
  script: >
    scli.sh --add_standby_mdm --mdm_role manager
    --new_mdm_ip {{ SCALEIO_MDM_FACTS.ip }}
    --new_mdm_name {{ CURRENT_MDM }}
  when: not SCALEIO_MDM_FACTS.joined | default(False) | bool

- name: Set {{ CURRENT_MDM }} joined fact
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  ini_file:
    path: /etc/dls-facts/scaleio.fact
    section: "{{ CURRENT_MDM }}"
    option: "{{ item.name }}"
    no_extra_spaces: True
    value: "{{ item.value }}"
    mode: 0640
    owner: cluster-facts
    group: cluster-facts
  when: item.name not in SCALEIO_MDM_FACTS
  with_items:
    - name: joined
      value: "True"

- include: synchronize-facts.yml

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"
