---

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"

- name: Load host facts
  set_fact:
    SCALEIO_TB_FACTS: "{{ (ansible_local.scaleio | default({}))[CURRENT_TB] | default({}) }}"

- name: Set {{ CURRENT_TB }} node fact
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  ini_file:
    path: /etc/dls-facts/scaleio.fact
    section: "{{ CURRENT_TB }}"
    option: "{{ item.name }}"
    no_extra_spaces: True
    value: "{{ item.value }}"
    mode: 0640
    owner: cluster-facts
    group: cluster-facts
  when: item.name not in SCALEIO_TB_FACTS
  with_items:
    - name: ip
      value: "{{ hostvars[host].dls_configuration.data_interface.ipv4_address }}"
    - name: name
      value: "{{ hostvars[host].dls_configuration.network.instance_name }}"

- include: synchronize-facts.yml

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"

- name: Load host facts
  set_fact:
    SCALEIO_TB_FACTS: "{{ (ansible_local.scaleio | default({}))[CURRENT_TB] | default({}) }}"

- name: Fail if ip does not match
  fail:
    msg: "Ip for {{ CURRENT_TB }}: expected {{ SCALEIO_TB_FACTS.ip }} - got {{ hostvars[host].dls_configuration.data_interface.ipv4_address }}"
  when: SCALEIO_TB_FACTS.ip != hostvars[host].dls_configuration.data_interface.ipv4_address

- name: Fail if name does not match
  fail:
    msg: "Ip for {{ CURRENT_TB }}: expected {{ SCALEIO_TB_FACTS.name }} - got {{ hostvars[host].dls_configuration.network.instance_name }}"
  when: SCALEIO_TB_FACTS.name != hostvars[host].dls_configuration.network.instance_name

- name: Join mdm if did not join
  environment:
    SCLI_MDM: "{{ SCALEIO_MDM_0_FACTS.ip }}"
    SCLI_USERNAME: admin
    SCLI_PASSWORD: "{{ scaleio_password }}"
  script: >
    scli.sh --add_standby_mdm --mdm_role tb
    --new_mdm_ip {{ SCALEIO_TB_FACTS.ip }}
    --new_mdm_name {{ CURRENT_TB }}
  when: not SCALEIO_TB_FACTS.joined | default(False) | bool

- name: Set {{ CURRENT_TB }} joined fact
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  ini_file:
    path: /etc/dls-facts/scaleio.fact
    section: "{{ CURRENT_TB }}"
    option: "{{ item.name }}"
    no_extra_spaces: True
    value: "{{ item.value }}"
    mode: 0640
    owner: cluster-facts
    group: cluster-facts
  when: item.name not in SCALEIO_TB_FACTS
  with_items:
    - name: joined
      value: "True"

- include: synchronize-facts.yml

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"
