---

- name: Ensure that password provided in configuration is right
  fail:
    msg: Password does not match
  when:
    - "'password' in SCALEIO_CLUSTER_FACTS"
    - SCALEIO_CLUSTER_FACTS.password != scaleio_password | hash('sha256')

- name: Set password of it is required
  environment:
    SCLI_MDM: "{{ SCALEIO_MDM_0_FACTS.ip }}"
    SCLI_USERNAME: admin
    SCLI_PASSWORD: "admin"
  script: >
    scli.sh --set_password --old_password admin --new_password {{ scaleio_password }}
  when: "'password' not in SCALEIO_CLUSTER_FACTS"

- name: Set password fact
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  ini_file:
    path: /etc/dls-facts/scaleio.fact
    section: "cluster"
    option: "{{ item.name }}"
    no_extra_spaces: True
    value: "{{ item.value }}"
    mode: 0640
    owner: cluster-facts
    group: cluster-facts
  when: item.name not in SCALEIO_CLUSTER_FACTS
  with_items:
    - name: password
      value: "{{ scaleio_password | hash('sha256') }}"

- include: synchronize-facts.yml

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"

- name: Load host facts
  set_fact:
    SCALEIO_CLUSTER_FACTS: "{{ (ansible_local.scaleio | default({})).cluster | default({}) }}"
