---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: input-public
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 32Gi
  selector:
    matchLabels:
      app_name: {{ required "DLS4E Release name is required" .Values.global.dls4e }}
      share: public
      type: input
      user: {{ required "DLS4E Username is required as parameter user" .Values.username }}
  storageClassName: ""
