---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ required "DLS4E Release name is required" .Values.global.dls4e }}-{{ required "DLS4E Username is required as parameter username" .Values.username }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ required "DLS4E Username is required as parameter username" .Values.username }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
