apiVersion: {{ .Values.api_group_name }}/v1
kind: User
metadata:
  name: "{{ required "DLS4E Username is required as parameter user" .Values.username }}"
  labels:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service }}"
spec:
