---

- set_fact:
    repo_local_path: "/root/dls4e/repo/{{ dls4e_release_package_version }}-{{ dls4e_release_package_release }}"

- name: Ensure repo directory is present
  file:
    path: "{{ repo_local_path }}"
    state: directory

- name: Copy repository files
  vars:
    file_name: "dls4e-{{ item }}-{{ dls4e_release_package_version }}-{{ dls4e_release_package_release }}.x86_64.rpm"
  copy:
    src: "{{ file_name }}"
    dest: "{{ repo_local_path }}/{{ file_name }}"
  with_items:
    - commons
    - registry
    - yum
    - yum-repository

- name: Install package
  include_tasks: yum_static_install.yml
  vars:
    packages:
      - "{{ repo_local_path }}/dls4e-commons-{{ dls4e_release_package_version }}-{{ dls4e_release_package_release }}.x86_64.rpm"
    update_cache: True

- name: Install data
  include_tasks: yum_static_install.yml
  vars:
    packages:
      - "{{ repo_local_path }}/dls4e-yum-repository-{{ dls4e_release_package_version }}-{{ dls4e_release_package_release }}.x86_64.rpm"
      - "{{ repo_local_path }}/dls4e-yum-{{ dls4e_release_package_version }}-{{ dls4e_release_package_release }}.x86_64.rpm"
      - "{{ repo_local_path }}/dls4e-registry-{{ dls4e_release_package_version }}-{{ dls4e_release_package_release }}.x86_64.rpm"
