---

- name: Check if image exists
  shell: "helm status dls4enterprise"
  register: chart
  changed_when: chart.rc == 1
  failed_when: chart.rc not in [0, 1]

- name: Fail if upgrade is not possible
  fail:
    msg: DLS4E is already installed and upgrade option is not selected
  when:
    - not chart is changed
    - not (upgrade | default(False) | bool)

- name: Copy registry chart file
  copy:
    src: "dls4e-{{ dls4e_version }}.tgz"
    dest: "/tmp/dls4e-{{ dls4e_version }}.tgz"

- name: Set global values in configuration
  set_fact:
    global_values:
      dls4e_registry: "127.0.0.1:{{ registry_nodeport }}"
      dls4e_configuration:
        external_ip: "{{ dls_configuration.external_interface.ipv4_address }}"
        registry: "127.0.0.1:{{ registry_nodeport }}"
      images:
        - name: tiller
          value: "127.0.0.1:{{ registry_nodeport }}/dls4e/tiller:v2.8.1"
        - name: tensorflow
          value: "dls4e/tensorflow:1.8.0-py3"
        - name: tensorboard
          value: "dls4e/tensorflow:1.8.0-py3"

- name: Render configuration
  set_fact:
    dls4e_config_values:
      global: "{{ dls4e_configuration | default({}) | combine(global_values) }}"
      features: "{{ features | default({}) }}"

- name: Render values
  vars:
    rendered_values: "{{ features_config | default({}) | combine(dls4e_config_values) }}"
  copy:
    content: "{{ rendered_values | to_nice_yaml(width=50, explicit_start=True, explicit_end=True) }}"
    dest: "/tmp/dls4e-{{ dls4e_version }}.values.yaml"

- name: Install helm chart
  shell: "helm install -n dls4enterprise --namespace dls4e  /tmp/dls4e-{{ dls4e_version }}.tgz --wait -f /tmp/dls4e-{{ dls4e_version }}.values.yaml"
  when: chart is changed

- name: Upgrade helm chart
  shell: "helm upgrade dls4enterprise  /tmp/dls4e-{{ dls4e_version }}.tgz --wait -f /tmp/dls4e-{{ dls4e_version }}.values.yaml --recreate-pods"
  when:
    - not chart is changed
    - upgrade | default(False) | bool

- name: Remove image file
  file:
    path: "/tmp/dls4e-{{ dls4e_version }}.tgz"
    state: absent

- name: Remove image values file
  file:
    path: "/tmp/dls4e-{{ dls4e_version }}.values.yaml"
    state: absent
