# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

modelPath: ''
modelName: ''

restContainerPort: 8501
grpcContainerPort: 8500

image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ DLS4e.ExperimentImage }}

workersCount: 1

resources:
  requests:
    cpu: 0.01
    memory: 1Gi

experimentName: {{ DLS4e.ExperimentName }} 
podCount: 1
