---

- name: Set interface name
  set_fact:
    external_interface_fact: "ansible_{{ external_interface | default('') }}"

- name: Get external interface ip
  set_fact:
    instance_external_ip: "{{ hostvars[inventory_hostname][external_interface_fact].ipv4.address }}"
  when: external_interface_fact in hostvars[inventory_hostname]

- name: Calculate runtime external ip
  set_fact:
    runtime_external_ip: "{{ external_ip | default(instance_external_ip | default ('')) }}"

- name: Fail if external ip is not calculated
  fail:
    msg: Unable to calculate external ip
  when: not runtime_external_ip

- name: Add variable to localhost
  add_host:
    name: localhost
    runtime_external_ip: "{{ runtime_external_ip }}"
