apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-svc"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
