---

- name: Chekc if local repo file exists
  stat:
    path: /opt/carbon/yum/yum.conf

- name: Install yum nginx server
  environment: "{{ proxy }}"
  yum:
    conf_file: /opt/carbon/yum/yum.conf
    name: "{{ package_yum }}"
  loop_control:
    loop_var: package_yum
  with_items:
    - nginx
    - libselinux-python
  notify:
    - Reload Systemd
    - Restart Nginx

- seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  with_items: "{{ kubernetes_network.external_ports }}"

- seport:
    ports: 443-449
    proto: tcp
    setype: http_port_t
    state: present
