---

- name: Install local repo python installation
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}/install.yml"
        - "default_distribution.yml"
      paths:
        - ""
        - "{{ playbook_dir }}/tasks"

- name: Start and enable pcs service
  service:
    name: pcsd
    state: started
    enabled: True

- name: Reload facts
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"

- name: Generate hacluster user password
  changed_when: False
  shell: tr -d -c "a-zA-Z0-9" < /dev/urandom | head -c 20
  register: hacluster_password
  no_log: True

- name: Set hacluster user password for onetime auth
  changed_when: False
  shell: echo "{{ hacluster_password.stdout }}" | passwd --stdin hacluster
  no_log: True

- name: Setup cluster auth
  shell: >
    pcs cluster auth {{ hostvars[item].dls_configuration.network.instance_name }}
    -u hacluster -p "{{ hostvars[item].hacluster_password.stdout }}"
  when:
    - inventory_hostname == groups['kubernetes-master'][0]
  with_items: "{{ groups['kubernetes-master'] }}"
  no_log: True
  changed_when: False

- name: Create PCS cluster
  shell: >
    pcs cluster setup --name dls
    {% for item in groups['kubernetes-master'] %}{{ hostvars[item].dls_configuration.network.instance_name }} {% endfor %}
  when:
    - inventory_hostname == groups['kubernetes-master'][0]
    - not ((ansible_local.pcs | default({})).cluster | default({})).created | default(False) | bool

- name: Set cluster creation fact
  ini_file:
    path: /etc/dls-facts/pcs.fact
    section: "cluster"
    option: "created"
    no_extra_spaces: True
    value: "True"
    mode: 0640
    owner: cluster-facts
    group: cluster-facts
  when:
    - inventory_hostname == groups['kubernetes-master'][0]
  with_items: "{{ groups['kubernetes-master'] }}"

- include: synchronize-facts.yml
  when:
    - inventory_hostname == groups['kubernetes-master'][0]

- name: Start cluster on all nodes
  changed_when: False
  shell: pcs cluster start --all
  when:
    - inventory_hostname == groups['kubernetes-master'][0]

- name: Enable cluster on all nodes
  changed_when: False
  shell: pcs cluster enable --all
  when:
    - inventory_hostname == groups['kubernetes-master'][0]

- name: Dislable stonith
  shell: pcs property set stonith-enabled=false
  changed_when: False

- name: Set no quorum for single node
  shell: pcs property set no-quorum-policy=ignore
  changed_when: False
  when: groups['kubernetes-master'] | length < 3
