---

- name: Synchronize
  become_user: cluster-facts
  shell: "rsync -avhz --delete --progress /etc/dls-facts/ facts-{{ item }}:/etc/dls-facts/"
  changed_when: False
  with_items: "{{ groups['master'] }}"
  delegate_to: "{{ groups['master'][0] }}"
  when:
    - groups['master'][0] != item
