apiVersion: v1
kind: Pod
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  containers:
  - name: docker-registry
    image: registry:2
    imagePullPolicy: Always
    ports:
      - containerPort: 5000
