---

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"

- name: Set SDS disk name fact
  set_fact:
    SDS_DISK_NAME: "SDS_{{ hostvars[host].dls_configuration.data_interface.ipv4_address }}_{{ SDS_DISK }}"

- name: Load SDS disk facts
  set_fact:
    SCALEIO_SDS: "{{ ((ansible_local.scaleio | default({}))[SDS_DISK_NAME] | default({})) }}"

- name: Join SDS disk to cluster
  environment:
    SCLI_MDM: "{{ SCALEIO_MDM_IPS }}"
    SCLI_USERNAME: admin
    SCLI_PASSWORD: "{{ scaleio_password }}"
  script: >
    scli.sh --add_sds_device --sds_name {{ SDS_NAME }} --device_path {{ SDS_DISK }} --device_name {{ SDS_DISK_NAME }}
    --storage_pool_name {{ SCALEIO_STORAGE_POOL }}
  when: "'joined' not in SCALEIO_SDS"

- name: Set ScaleIO facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  ini_file:
    path: /etc/dls-facts/scaleio.fact
    section: "{{ SDS_DISK_NAME }}"
    option: "joined"
    no_extra_spaces: True
    value: "True"
    mode: 0640
    owner: cluster-facts
    group: cluster-facts

- include: synchronize-facts.yml
