---

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"

- name: Load MDM ips facts
  set_fact:
    SCALEIO_MDM_IPS: "{{ ((ansible_local.scaleio | default({}))['cluster'] | default({})).ips }}"
    SCALEIO_STORAGE_POOL: "{{ ((ansible_local.scaleio | default({}))['cluster'] | default({})).storage_pool }}"
    SCALEIO_PROTECTION_DOMAIN: "{{ ((ansible_local.scaleio | default({}))['cluster'] | default({})).protection_domain }}"
    SCALEIO: "{{ (ansible_local.scaleio | default({})) }}"

- name: Join all sds in cluster
  include_tasks: join.yml
  with_items: "{{ groups['scaleio-all'] }}"
  loop_control:
    loop_var: host
  when:
    - hostvars[host].dls_configuration.data_interface.ipv4_address in SCALEIO
    - SCALEIO[hostvars[host].dls_configuration.data_interface.ipv4_address].sds == 'single'

- name: Join all multi sds in cluster
  include_tasks: multi.yml
  with_items: "{{ groups['scaleio-all'] }}"
  loop_control:
    loop_var: host
  when:
    - hostvars[host].dls_configuration.data_interface.ipv4_address in SCALEIO
    - SCALEIO[hostvars[host].dls_configuration.data_interface.ipv4_address].sds == 'multi'
