---

- hosts: all
  become: True
  any_errors_fatal: True
  roles:
    - role: cluster/init/ca.prepare
      tags:
        - install

- hosts: kubernetes-master[0]
  become: True
  become_user: cluster-master
  any_errors_fatal: True
  roles:
    - role: cluster/init/ca.init
      tags:
        - install
