apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
      - name: users-database-vol
        secret:
          secretName: users-database-secret
      containers:
      - name: {{ .Chart.Name }}
        image: {{ required "Samba IMAGE is required" .Values.SambaImage }}
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: users-database-vol
          readOnly: true
          mountPath: "/etc/secrets/samba-users"
        resources:
          limits:
            memory: 512Mi
        ports:
        - containerPort: 137
          protocol: UDP
        - containerPort: 138
          protocol: UDP
        - containerPort: 139
          protocol: TCP
        - containerPort: 445
          protocol: TCP
