apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-svc"
spec:
  type: ClusterIP
  clusterIP: {{ required "Samba ClusterIP is required" .Values.ClusterIP }}
  ports:
    - port: 139
      targetPort: 139
      protocol: TCP
      name: "samba-tcp-139"
    - port: 445
      targetPort: 445
      protocol: TCP
      name: "samba-tcp-445"
    - port: 137
      targetPort: 137
      protocol: UDP
      name: "samba-udp-137"
    - port: 138
      targetPort: 138
      protocol: UDP
      name: "samba-udp-138"
  selector:
    app: {{ .Chart.Name }}

