apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    dls4e_release: {{ required "DLS4E Release name is required" .Values.global.dls4e }}
    dls4e_release_version: {{ required "DLS4E Release version is required" .Values.global.dls4e_release }}
    dls4e_app_name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        heritage: {{ .Release.Service }}
        dls4e_app_name: samba
    spec:
      volumes:
        - name: input
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Chart.Name }}-input
        - name: output
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Chart.Name }}-output
      serviceAccountName: {{ .Release.Name }}-{{ .Chart.Name }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ required "DLS4E Registry is required" .Values.global.dls4e_registry }}/{{ required "DLS4E samba image is required" .Values.image }}
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: 512Mi
        env:
        - name: INPUT_PVC
          value: {{ .Release.Name }}-{{ .Chart.Name }}-input
        - name: OUTPUT_PVC
          value: {{ .Release.Name }}-{{ .Chart.Name }}-output
        - name: APP_RELEASE
          value: {{ .Release.Name }}
        - name: SAMBA_LOG_LEVEL
          value: "10"
        ports:
        - containerPort: 137
          protocol: UDP
        - containerPort: 138
          protocol: UDP
        - containerPort: 139
          protocol: TCP
        - containerPort: 445
          protocol: TCP
        volumeMounts:
          - name: input
            mountPath: /input
          - name: output
            mountPath: /output
