apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ingress-defaultbackend
  labels:
    app: {{ .Release.Name }}-ingress-defaultbackend
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ingress-defaultbackend
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ingress-defaultbackend
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        image: {{ required "DefaultBackend IMAGE is required" .Values.DefaultBackendImage }}
        resources:
          requests:
            cpu: 100m
            memory: 64m
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
