---

- name: Check if carbon python file exists
  file:
    path: /opt/carbon/python/bin/python2

- name: Set python fact
  set_fact:
    ansible_python_interpreter: "/opt/carbon/python/bin/python2"

- name: Setup node facts
  setup:

- name: Check if image exists
  shell: "docker inspect dls4e-repository:{{ dls4e_version }}"
  register: image
  changed_when: image.rc == 1
  failed_when: image.rc not in [0, 1]

- name: Copy image file
  copy:
    src: "dls4e-{{ dls4e_version }}.img"
    dest: "/tmp/dls4e-{{ dls4e_version }}.img"
  when: image is changed

- name: Load image file
  shell: "docker load -i /tmp/dls4e-{{ dls4e_version }}.img"
  when: image is changed

- name: Remove image file
  file:
    path: "/tmp/dls4e-{{ dls4e_version }}.img"
    state: absent
  when: image is changed

- name: Ensure image exists
  shell: "docker inspect dls4e-repository:{{ dls4e_version }}"

- name: Label node
  shell: "kubectl label node {{ ansible_nodename }} dls4e-release-version-{{ dls4e_version.replace('.', '-') }}=True --overwrite"

- name: Create a k8s dls4e namespace
  shell: "kubectl get namespace dls4e || kubectl create namespace dls4e"
