---

- name: "{{ message_label }} Load informations about admin user"
  environment: "{{ local_envs }}"
  shell: "{{ runtime_kubectl }} -n dls4e get serviceaccounts dls4enterprise-admin-account -o jsonpath='{.secrets[0].name}'"
  register: dlsenterprise_admin_account

- name: "{{ message_label }} Load informations about admin token"
  environment: "{{ local_envs }}"
  shell: "{{ runtime_kubectl }} -n dls4e get secrets {{ dlsenterprise_admin_account.stdout }} -o jsonpath='{.data.token}'"
  register: dlsenterprise_admin_token

- name: "{{ message_label }} Load informations about admin namespace"
  environment: "{{ local_envs }}"
  shell: "{{ runtime_kubectl }} -n dls4e get secrets {{ dlsenterprise_admin_account.stdout }} -o jsonpath='{.data.namespace}'"
  register: dlsenterprise_admin_namespace

- name: "{{ message_label }} Load informations about admin crt"
  environment: "{{ local_envs }}"
  shell: "{{ runtime_kubectl }} -n dls4e get secrets {{ dlsenterprise_admin_account.stdout }} -o jsonpath='{.data.ca\\.crt}'"
  register: dlsenterprise_admin_crt

- name: "{{ message_label }} Create kube directory"
  file:
    path: "~/.kube"
    state: directory

- name: "{{ message_label }} Render dls4enterprise admin config"
  template:
    src: kubeconfig.yml.j2
    dest: "{{ root }}/dls4e-admin.config"
