---

- name: Copy template for {{ name }}
  template:
    src: "{{ name }}"
    dest: "/root/rpmbuild/SPECS/{{ name }}"

- name: Run rpmbuild for repository
  changed_when: False
  shell: "rpmbuild -bb -v /root/rpmbuild/SPECS/{{ name }}"
