---

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /repo/packages
    - /tmp_dir

- name: Create repository directories
  file:
    path: "/root/rpmbuild/{{ item }}"
    state: directory
  with_items:
    - BUILD
    - BUILDROOT
    - RPMS
    - SOURCES
    - SPECS
    - SRPMS

- name: Download all packages
  changed_when: False
  shell: yum-carbon install -y --downloadonly --downloaddir=/repo/packages --releasever=7 --installroot=/tmp_dir {{ yum_packages | join(' ') }}

- name: Include pre build tasks
  include_tasks: createrepo.yml
  loop_control:
    loop_var: name
  with_items:
    - carbon-python

- name: List all rpms
  find:
    path: /root/rpmbuild/RPMS/x86_64/
    patterns: '*.rpm'
  register: files

- name: Download all generated packages
  changed_when: False
  shell: yum-carbon install -y --downloadonly --downloaddir=/repo/packages --releasever=7 --installroot=/tmp_dir {{ item.path }}
  with_items: "{{ files.files }}"

- name: Copy all rpms
  copy:
    remote_src: True
    src: "{{ item.path }}"
    dest: "/repo/packages/{{ item.path | basename }}"
  with_items: "{{ files.files }}"

- name: Create repository
  changed_when: False
  shell: createrepo .
  args:
    chdir: /repo

- name: Remove all files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files.files }}"

- name: Create ansible archive
  shell: tar -zvcf /root/rpmbuild/SOURCES/package.tar.gz /repo/

- name: Create docker archive
  shell: tar -zvcf /root/rpmbuild/SOURCES/docker.tar.gz docker/
  args:
    chdir: /output

- name: Include post build tasks
  include_tasks: createrepo.yml
  loop_control:
    loop_var: name
  with_items:
    - carbon-package
    - carbon-registry
    - carbon-local-repository

- name: List all rpms
  find:
    path: /root/rpmbuild/RPMS/x86_64/
    patterns: '*.rpm'
  register: files

- name: Copy all rpms
  copy:
    remote_src: True
    src: "{{ item.path }}"
    dest: "/output/{{ item.path | basename }}"
  with_items: "{{ files.files }}"
