apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    dls4e_release: {{ required "DLS4E Release name is required" .Values.global.dls4e }}
    dls4e_release_version: {{ required "DLS4E Release version is required" .Values.global.dls4e_release }}
data:
  nginx.conf: |-
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;
    include /usr/share/nginx/modules/*.conf;
    events {
      worker_connections 1024;
      multi_accept on;
    }
    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;
      gzip on;
      gzip_disable "msie6";
      server {
        listen 5000;
        client_max_body_size 0;
        client_body_buffer_size 128k;
        location /v2/dls4e/ {
          proxy_pass http://{{ .Release.Name }}-registry-{{ .Values.global.dls4e_release_standarized }}:5000/v2/dls4e/;
          proxy_set_header  Host           $http_host;   # required for docker client's sake
          proxy_set_header  X-Real-IP      $remote_addr; # pass on real client's IP
          proxy_set_header  Authorization  ""; # see https://github.com/dotcloud/docker-registry/issues/170
          proxy_read_timeout               900;
        }
        location / {
          proxy_pass http://{{ .Release.Name }}-docker-registry:5000/;
          proxy_set_header  Host           $http_host;   # required for docker client's sake
          proxy_set_header  X-Real-IP      $remote_addr; # pass on real client's IP
          proxy_set_header  Authorization  ""; # see https://github.com/dotcloud/docker-registry/issues/170
          proxy_read_timeout               900;
        }
      }
    }
