apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 32111
    protocol: TCP
  selector:
    app: docker-registry
