---

- name: Chekc if local repo file exists
  stat:
    path: /opt/carbon/yum/yum.conf

- name: Install yum rsync
  environment: "{{ proxy }}"
  yum:
    conf_file: /opt/carbon/yum/yum.conf
    name: "{{ package }}"
  loop_control:
    loop_var: package
  with_items:
    - rsync

- name: Remove yum packages
  environment: "{{ proxy }}"
  yum:
    conf_file: /opt/carbon/yum/yum.conf
    name: "{{ package }}"
    state: absent
  loop_control:
    loop_var: package
  with_items:
    - firewall
