---

- name: Fail if carbon_release_package_repofile is not set
  fail:
    msg: Before installation carbon_release_package_repofile should be set
  when: carbon_release_package_repofile is not defined

- name: Download repo
  environment: "{{ proxy }}"
  get_url:
    url: "{{ carbon_release_package_repofile }}"
    dest: "/etc/yum.repos.d/carbon.repo"
    force: True

- name: Refresh yum repository
  environment: "{{ proxy }}"
  yum:
    disable_plugin: '*'
    disablerepo: '*'
    enablerepo: carbon
    list: '*'
    update_cache: True

- name: Install carbon-yum-repository package
  environment: "{{ proxy }}"
  yum:
    state: installed
    disable_plugin: '*'
    disablerepo: '*'
    enablerepo: carbon
    name: "{{ pack }}"
    update_cache: True
    allow_downgrade: True
  loop_control:
    loop_var: pack
  with_items:
    - "carbon-yum-repository-{{ carbon_release_package_version }}-{{ carbon_release_package_release }}"
    - "carbon-yum-local-{{ carbon_release_package_version }}-{{ carbon_release_package_release }}"

- name: Install carbon-yum-local package
  environment: "{{ proxy }}"
  yum:
    disable_plugin: '*'
    disablerepo: '*'
    enablerepo: carbon
    name: "carbon-registry-repository-{{ carbon_release_package_version }}-{{ carbon_release_package_release }}"
    update_cache: True
    allow_downgrade: True
    state: installed
  when: inventory_hostname in groups['master']
