---

- name: Push image {{ name }} as 127.0.0.1:{{ registry_port }}/{{ name }}:{{ image.version }}
  docker_image:
    name: "127.0.0.1:{{ registry_port }}/{{ name }}:{{ image.version }}"
    pull: False
    push: True
    timeout: "{{ docker_timeout }}"
  register: push_async
  failed_when: "'ansible_job_id' not in push_async"
  async: 1800
  poll: 0

- set_fact:
    docker_async_tasks: "{{ docker_async_tasks | combine({name: push_async.ansible_job_id}) }}"
