---

- name: Set async task
  set_fact:
    docker_async_tasks: {}

- name: Save all images
  vars:
    name: "{{ item.key }}"
    image: "{{ item.value }}"
  include_tasks: "save_image.yml"
  with_dict: "{{ images }}"
  when: not docker_images_remote_exists[name]

- name: Wait for tasks
  vars:
    name: "{{ item.key }}"
    task_id: "{{ item.value }}"
  include_tasks: wait.yml
  with_dict: "{{ docker_async_tasks }}"
