---

- name: Tag image "{{ docker_repository_registry }}/{{ docker_version_prefix }}/{{ name }}:{{ docker_images_remote_tags[name] }}" as {{ name }}:{{ image.version }}
  docker_image:
    name: "{{ docker_repository_registry }}/{{ docker_version_prefix }}/{{ name }}:{{ docker_images_remote_tags[name] }}"
    repository: "{{ name }}:{{ image.version }}"
    push: False
    timeout: "{{ docker_timeout }}"
    force: True
  register: tag_async
  failed_when: "'ansible_job_id' not in tag_async"
  async: 1800
  poll: 0

- set_fact:
    docker_async_tasks: "{{ docker_async_tasks | combine({name: tag_async.ansible_job_id}) }}"
