---

- name: Set storage type
  set_fact:
    detected_storage_type: local
    detected_storage_path: "{{ master_storage_path }}"
    detected_storage_selector: "{{ master_storage_selector }}"

- name: Set storage fact
  set_fact:
    calculated_storage:
      type: "{{ detected_storage_type }}"
      local_path: "{{ detected_storage_path }}"
      local_selector: "{{ detected_storage_selector }}"
