apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vertical-resizer
  labels:
    app: {{ .Release.Name }}-nanny
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nanny
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nanny
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ .Release.Name }}-nanny
      containers:
      - name: nanny
        image: {{ required "AddonResizer IMAGE is required" .Values.AddonResizerImage }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 50m
            memory: 90Mi
          requests:
            cpu: 50m
            memory: 90Mi
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - "/pod_nanny"
          - "--deployment=heapster"
          - "--container={{ .Release.Name }}"
          - "--cpu=150m"
          - "--extra-cpu=10m"
          - "--memory=200Mi"
          - "--extra-memory=6Mi"
          - "--threshold=5"
          - "--poll-period=300000"
