apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: "{{ .Release.Name }}-view"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{ .Values.api_group_name }}/view: "true"
  name: dls4enterprise-heapster-view
rules:
- apiGroups:
  - "*"
  resources:
  - "services"
  resourceNames:
  - "heapster"
  - "dls4enterprise-k8s-platform-heapster"
  verbs:
  - "proxy"
  - "get"
- apiGroups:
  - "*"
  resources:
  - "services/proxy"
  resourceNames:
  - "heapster"
  - "http:heapster:"
  - "https:heapster:"
  - "http:dls4enterprise-k8s-platform-heapster:"
  - "https:dls4enterprise-k8s-platform-heapster:"
  verbs:
  - "get"
  - "list"
  - "create"
