# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

TensorBoardPort: 8888
TensorIPythonPort: 6006

commandline:
  args:
    - "/app/training.py"
    - "--data_dir=/temp"

image:
  pullPolicy: IfNotPresent
  clusterRepository: ''

service:
  type: ClusterIP

resources:
  requests:
    cpu: 38
    memory: 120Gi
  limits:
    cpu: 38
    memory: 120Gi


experimentName: ''
podCount: 1
