---

- become: False
  gather_facts: True
  hosts: localhost
  connection: local
  any_errors_fatal: True
  max_fail_percentage: 0
  roles:
    - role: dls.kubernetes.feature
      tags:
        - always
