# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dataPath: '/mnt/input/home/data'
modelPath: '/mnt/input/home/models'
modelName: 'mnist'
outputPath: '/mnt/output/experiment'

containerPort: 8500

image:
  pullPolicy: IfNotPresent
  clusterRepository: ''

workersCount: 1

resources:
  requests:
    cpu: 0.01
    memory: 1Gi

experimentName: ''
podCount: 2

logLevel: 'INFO'
