---

- name: Include distribution based task
  include_tasks: "{{ distribution_resolved_file }}"
  loop_control:
    loop_var: distribution_resolved_file
  with_first_found:
    - files:
        - "{{ ansible_distribution }}/{{ distribution_file }}"
        - "default_distribution.yml"
      paths:
        - "{{ role_path }}/tasks"
        - "{{ playbook_dir }}/tasks"
