---

- name: Ensure remove of {{ packages | join(', ') }}
  environment: "{{ proxy }}"
  yum:
    disable_plugin: "*"
    update_cache: "False"
    disablerepo: "*"
    name: "{{ item }}"
    state: "absent"
  with_items: "{{ packages }}"
