---

- name: "{{ message_label }} Ensure existence of {{ packages | join(', ') }}"
  environment: "{{ proxy }}"
  yum:
    disable_plugin: "*"
    update_cache: "False"
    disablerepo: "*"
    name: "{{ item }}"
    state: "present"
  with_items: "{{ packages }}"
