---
- name: Check all build dependencies are installed
  hosts: localhost
  become: False
  roles:
    - role: check-dependency
      binary: python3
    - role: check-dependency
      binary: pip
    - role: check-dependency
      binary: virtualenv
    - role: check-dependency
      binary: tar
    - role: check-dependency
      binary: pigz
    - role: check-dependency
      binary: docker

- name: Run local tasks
  hosts: localhost
  become: False
  handlers:
    - name: Cleanup registry container
      docker_container:
        name: "{{ registry_name }}"
        state: absent
  roles:
    - role: cache-registry-init
      when: not docker_repository_cache.external
    - role: prepare
    - role: container-build
    - role: finalize
    - role: cache-registry-final
      when: not docker_repository_cache.external
