---

- name: Chekc if local repo file exists
  stat:
    path: /opt/carbon/yum/yum.conf

- name: Install yum nginx server
  environment: "{{ proxy }}"
  yum:
    conf_file: /opt/carbon/yum/yum.conf
    name: "{{ package_yum }}"
  loop_control:
    loop_var: package_yum
  with_items:
    - nginx
    - libselinux-python
  notify:
    - Reload Systemd
    - Restart Nginx

- name: Disable SELinux
  selinux:
    state: disabled
