---

- name: Create required groups for cluster facts synchronization
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
  with_items:
    - name: cluster-facts
      gid: 3510

- name: Ensure that home dir exists
  file:
    path: /opt/carbon/home
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create required users for cluster synchronization
  user:
    name: "{{ item.name }}"
    create_home: True
    generate_ssh_key: True
    groups: cluster-facts
    uid: "{{ item.uid }}"
    home: "/opt/carbon/home/{{ item.name }}"
  with_items:
    - name: cluster-facts
      uid: 3510

- name: Install local repo python installation
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}/install.yml"
        - "default_distribution.yml"
      paths:
        - ""
        - "{{ playbook_dir }}/tasks"

- name: Fetch public keys from hosts
  slurp:
    src: "/opt/carbon/home/cluster-facts/.ssh/id_rsa.pub"
  register: cluster_facts_key

- name: Add authorized master keys to facts users
  authorized_key:
    user: cluster-facts
    key: "{{ hostvars[item].cluster_facts_key.content | b64decode }}"
  with_items: "{{ groups['kubernetes-master'] }}"

- name: Render facts key config
  template:
    src: config.j2
    dest: /opt/carbon/home/cluster-facts/.ssh/config
    mode: 0600
    owner: cluster-facts
    group: cluster-facts
  when: inventory_hostname in groups['kubernetes-master']

- name: Create cluster directory
  file:
    path: /etc/dls-facts
    state: directory
    owner: cluster-facts
    group: cluster-facts
    mode: 0750
