---

- name: Create directory for exports
  file:
    path: /export
    state: directory
    owner: nfsnobody
    group: nfsnobody

- name: Create xfs on nfs_disk device
  filesystem:
    dev: "{{ nfs_device }}"
    fstype: xfs
    resizefs: True

- name: Mount xfs for nfs
  mount:
    fstype: xfs
    path: /export
    state: mounted
    src: "{{ nfs_device }}"

- name: Create directory for exports
  file:
    path: "/export/{{ item }}"
    state: directory
    owner: nfsnobody
    group: nfsnobody
  with_items:
    - input
    - output
