---

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"

- name: Load MDM ips facts
  set_fact:
    SCALEIO_CLUSTER: "{{ ((ansible_local.scaleio | default({}))['cluster'] | default({})) }}"

- name: Create protection domain
  environment:
    SCLI_MDM: "{{ SCALEIO_CLUSTER.ips }}"
    SCLI_USERNAME: admin
    SCLI_PASSWORD: "{{ scaleio_password }}"
  script: >
    scli.sh --add_protection_domain --protection_domain_name {{ scaleio_protection_domain }}
  when:
    - "'protection_domain' not in SCALEIO_CLUSTER"

- name: Create storage pool
  environment:
    SCLI_MDM: "{{ SCALEIO_CLUSTER.ips }}"
    SCLI_USERNAME: admin
    SCLI_PASSWORD: "{{ scaleio_password }}"
  script: >
    scli.sh --add_storage_pool --storage_pool_name {{ scaleio_storage_pool }} --protection_domain_name {{ scaleio_protection_domain }}
  when:
    - "'storage_pool' not in SCALEIO_CLUSTER"

- name: Set ScaleIO facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  ini_file:
    path: /etc/dls-facts/scaleio.fact
    section: "cluster"
    option: "{{ item.name }}"
    no_extra_spaces: True
    value: "{{ item.value }}"
    mode: 0640
    owner: cluster-facts
    group: cluster-facts
  when: item.name not in SCALEIO_CLUSTER
  with_items:
    - name: protection_domain
      value: "{{ scaleio_protection_domain }}"
    - name: storage_pool
      value: "{{ scaleio_storage_pool }}"

- include: synchronize-facts.yml

- name: Reload facts
  delegate_to: "{{ groups['kubernetes-master'][0] }}"
  setup:
    fact_path: /etc/dls-facts
    gather_subset: "!all"
