---

- name: Ensure that directory exists
  file:
    path: "{{ build_dir }}/bin/{{ name }}"
    state: directory

- name: Download all files
  environment: "{{ proxy }}"
  vars:
    path: "{{ build_dir }}/bin/{{ name }}/{{ item.key }}"
    url: "{{ item.value.url }}"
    sha: "{{ item.value.shasum }}"
  with_dict: "{{ spec }}"
  get_url:
    url: "{{ url }}"
    dest: "{{ path }}"
    checksum: "sha256:{{ sha }}"
