# list of workers
{{- $zk := dict "workers" (list) -}}
{{- range int (.Values.multinode.workers_count|int) | until -}}
{{- $noop := printf "worker-service-%d-%s-%s:%d" . $.Release.Name $.Values.user.name ($.Values.multinode.port|int) | append $zk.workers | set $zk "workers" -}}
{{- end -}}
{{- $worker_names := join "," $zk.workers }}
# list of parameter servers
{{- $zk := dict "pss" (list) -}}
{{- range int (.Values.multinode.ps_count|int) | until -}}
{{- $noop := printf "ps-service-%d-%s-%s:%d" . $.Release.Name $.Values.user.name ($.Values.multinode.port|int) | append $zk.pss | set $zk "pss" -}}
{{- end -}}
{{- $ps_names := join "," $zk.pss -}}

{{- $command_args := join "\", \"" $.Values.training.args }}

{{- range $i, $e := until (.Values.multinode.ps_count|int) }}
apiVersion: v1
kind: Pod
metadata:
  name: training-pod-ps-{{ $i }}-{{ $.Release.Name }}-{{ $.Values.user.name }}
  labels:
    app: training-pod-ps-{{ $i }}-{{ $.Release.Name }}-{{ $.Values.user.name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: "{{ $.Release.Revision }}"
spec:
  restartPolicy: OnFailure
  containers:
  - name: training-container
    image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
    command: ["python"]
    args: ["-u", {{ $.Values.training.script_name }}, "{{ $.Values.training.task_id_param_name }}={{ $i }}",  "{{ $.Values.training.job_name_param }}=ps", "{{ $.Values.training.ps_list_param_name }}={{ $ps_names }}", "{{ $.Values.training.workers_list_param_name }}={{ $worker_names }}", "{{ $command_args }}" ]
    ports:
    - containerPort: {{ $.Values.multinode.port }}
    securityContext:
      privileged: true
{{- if $.Values.ps_resources -}}{{- toYaml $.Values.ps_resources | indent 4 -}}{{- end }}
{{ printf "---\n" }}
{{- end -}}
{{- range $i, $e := until (.Values.multinode.workers_count|int) -}}
apiVersion: v1
kind: Pod
metadata:
  name: training-pod-worker-{{ $i }}-{{ $.Release.Name }}-{{ $.Values.user.name }}
  labels:
    app: training-pod-worker-{{ $i }}-{{ $.Release.Name }}-{{ $.Values.user.name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: "{{ $.Release.Revision }}"
spec:
  restartPolicy: OnFailure
  containers:
  - name: training-container
    image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
    command: ["python"]
    args: ["-u", {{ $.Values.training.script_name }}, "{{ $.Values.training.task_id_param_name }}={{ $i }}",  "{{ $.Values.training.job_name_param }}=worker", "{{ $.Values.training.ps_list_param_name }}={{ $ps_names }}", "{{ $.Values.training.workers_list_param_name }}={{ $worker_names }}", "{{ $command_args }}" ]
    ports:
    - containerPort: {{ $.Values.multinode.port }}
    securityContext:
      privileged: true
{{ if $.Values.worker_resources }}{{ toYaml $.Values.worker_resources | indent 4 }}{{- end }}
{{ if ne ($.Values.multinode.workers_count|int) (add $i 1) }}{{ printf "---\n" }}
{{- end -}}
{{- end -}}
