---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dls4e-access
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - experiments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - runs
    verbs:
      - get
      - list
      - watch
