---

- include_tasks: include_distribution.yml
  vars:
    distribution_file: install.yml

- meta: flush_handlers

- name: Create http configuration path
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Create docker configuration path
  file:
    path: /etc/docker
    state: directory

- name: Render proxy configuration
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/{{ item }}.conf"
  with_items:
    - proxy
    - consul
  notify:
    - Reload Systemd
    - Restart Docker

- name: Render docker configuration
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - Restart Docker

- meta: flush_handlers

- name: Start and enable docker
  service:
    name: docker
    state: started
    enabled: True
