---

- name: Create release directories
  file:
    path: "/release/{{ item }}"
    state: directory
  with_items:
    - bin
    - tmp

- name: Create virtualenv
  environment: "{{ proxy }}"
  pip:
    name: "pyinstaller==3.3.1"
    virtualenv_python: python3.6
    virtualenv_site_packages: False
    virtualenv: /venv

- name: Install all requirements
  environment: "{{ proxy }}"
  pip:
    name: "{{ item }}"
    virtualenv: /venv
    virtualenv_python: python3.6
    virtualenv_site_packages: False
  with_items: "{{ pip_packages }}"

- name: Create ansible package
  shell: >
    /venv/bin/pyinstaller
    -F "/venv/bin/ansible-playbook"
    -n "ansible-playbook"
    --specpath "/venv"
    --clean
    --distpath "/release/bin"
    --hidden-import "jmespath"
    --hidden-import "ansible"
    --hidden-import "docker"
    --hidden-import "configparser"
    --hidden-import "netaddr"
    --hidden-import "smtplib"
    --hidden-import "logging.handlers"
    --hidden-import "pty"
    --hidden-import "crypt"
    --hidden-import "xml.etree"
    --hidden-import "xml.etree.ElementTree"
    --add-data /venv/lib/python3.6/site-packages/ansible:ansible
  args:
    chdir: "/venv"

- name: Copy ansible package
  copy:
    remote_src: True
    src: /release/bin/ansible-playbook
    dest: /out/ansible-playbook
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
    mode: 0755
