---

proxy:
  http_proxy: http://proxy-mu.intel.com:911
  https_proxy: http://proxy-mu.intel.com:912
  no_proxy: os.mirror,.intel.com,127.0.0.1,localhost

images: "{{ shared_images | combine(local_images | default({})) }}"

shared_images:
  shared/ubuntu:
    version: "16.04"
    method: "pull"
    push: False
    image: "ubuntu:16.04"
  shared/nonredist/ubuntu1804:
    version: "18.04"
    method: "pull"
    push: False
    image: "ubuntu:bionic-20180821"
  shared/centos:
    version: "7.5.1804"
    method: "build"
    push: False
    directory: "{{ playbook_dir }}/../../shared-containers/centos/core"
    required: {}
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/centos/centos-docker-0008.tar.xz
        dest: centos-docker.tar.xz
        checksum: d5759d1da5f8a1e70f29b7dacfe5458fb2edf86fc2679115e5a71eca463bfa42
  shared/centos/rpm-packer:
    version: "7.5.1804"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/rpm-packer"
    push: False
  shared/centos/docs:
    version: "7.5.1804"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../docs/end-user-docs/user-guide/HTML Files: Source and Output/HTML-Output"
    dockerfile: "{{ playbook_dir }}/../../shared-containers/docs/Dockerfile"
    push: False
  shared/centos/build:
    version: "7.5.1804"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build"
    push: False
  shared/centos/python27:
    version: "2.7"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/python27"
    push: False
  shared/centos/python36:
    version: "3.6"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/python36"
    push: False
  shared/centos/build-go:
    version: "1.10.2"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build-go"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/go/go1.10.2.linux-amd64.tar.gz
        dest: go1.10.2.linux-amd64.tar.gz
        checksum: 4b677d698c65370afa33757b6954ade60347aaca310ea92a63ed717d7cb0c2ff
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/godep/dep-linux-amd64
        dest: dep-linux-amd64
        checksum: 31144e465e52ffbc0035248a10ddea61a09bf28b00784fd3fdd9882c8cbb2315
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/glide/glide-v0.13.1-linux-amd64
        dest: glide-v0.13.1-linux-amd64
        checksum: b3e126a0034ab41005b51fc9542997b632f2802ee64ad0e3850c0353ba2867cf
  shared/centos/java8:
    version: "8"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/java8"
    push: False
  shared/centos/go-apiserver-builder:
    version: "v1.9-alpha.4"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/go-apiserver-builder"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/apiserver-builder/apiserver-builder-v1.9-alpha.4-linux-amd64.tar.gz
        dest: apiserver-builder-v1.9-alpha.4-linux-amd64.tar.gz
        checksum: 6f82bb4d063b46a920f2952debd9ade19e712e7472d43e97ff09a2bf2f705ca6
  shared/build/kubernetes:
    version: "v1.10.6"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/kubernetes"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/kubernetes/v1.10.6.tar.gz
        dest: kubernetes.tar.gz
        checksum: d91a77a65199f835ad68372fabd99a1f764ec59d9bde222c74224c1bf976ab20
  shared/build/nginx:
    version: "v1.13.9"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/nginx"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/nginx/nginx-1.13.9-1.el7_4.ngx.src.rpm
        dest: nginx-1.13.9-1.el7_4.ngx.src.rpm
        checksum: 98d4329318dc9a681fa5e13cba5bc809bd2f7a97e38b36a1d07cb15a53b855ee
  shared/build/tensorflow/py2.7:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python27"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/2.7/build"
    push: False
  shared/build/tensorflow/py3.6:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/3.6/build"
    push: False
  shared/build/tensorflow/py2.7/1.9.0:
    version: "1.9.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/1.9.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/mkl/v1.9.0.tar.gz
        dest: tensorflow-v1.9.0.tar.gz
        checksum: ffc3151b06823d57b4a408261ba8efe53601563dfe93af0866751d4f6ca5068c
  shared/build/tensorflow/py3.6/1.9.0:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/1.9.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/mkl/v1.9.0.tar.gz
        dest: tensorflow-v1.9.0.tar.gz
        checksum: ffc3151b06823d57b4a408261ba8efe53601563dfe93af0866751d4f6ca5068c
  shared/build/tensorflow/py2.7/1.9.0/haswell:
    version: "1.9.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/haswell"
    push: False
  shared/build/tensorflow/py3.6/1.9.0/haswell:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/haswell"
    push: False
  shared/build/tensorflow/py3.6/1.9.0/skylake:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/skylake"
    push: False
  shared/build/tensorflow-serving/py2.7/1.9.0:
    version: "1.9.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/1.9.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/tf-serving/1.9.0.tar.gz
        dest: tensorflow-serving-v1.9.0.tar.gz
        checksum: 860fc67fe6d385f721bf98b533d6cabb09162f8b1469e69af3c7e9f30dde0b92
  shared/build/tensorflow-serving/py3.6/1.9.0:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/1.9.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/tf-serving/1.9.0.tar.gz
        dest: tensorflow-serving-v1.9.0.tar.gz
        checksum: 860fc67fe6d385f721bf98b533d6cabb09162f8b1469e69af3c7e9f30dde0b92
  shared/build/tensorflow-serving/py2.7/1.9.0/haswell:
    version: "1.9.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow-serving/py2.7/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/haswell"
    push: False
  shared/build/tensorflow-serving/py3.6/1.9.0/haswell:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow-serving/py3.6/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/haswell"
    push: False
  shared/build/tensorflow-serving/py3.6/1.9.0/skylake:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow-serving/py3.6/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/skylake"
    push: False
  shared/run/tensorflow/py2.7:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python27"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/run"
    push: False
    args:
      PYTHON_VERSION: 2.7
  shared/run/tensorflow/py3.6:
    version: "py3"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/run"
    push: False
    args:
      PYTHON_VERSION: 3.6
  shared/build/helm:
    version: "v2.9.1"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/helm"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/helm/v2.9.1.tar.gz
        dest: helm.tar.gz
        checksum: 2fee31764117024d1cc4f597d23791c60feef7c3ceedd143cfdbbafca7a7e126
  shared/build/cni:
    version: "v0.7.1"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/cni"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/cni-plugins/v0.7.1.tar.gz
        dest: cni-plugins.tar.gz
        checksum: 6939d7fe0340879223cd3675b2cd1a13a41170781740cf5f856a4b06e379ffcb
  shared/build/etcd:
    version: "3.3.9"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/etcd"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/etcd/v3.3.9.tar.gz
        dest: etcd-v3.3.9.tar.gz
        checksum: 96639d35772108004da53e568489ce7572171d39ee507245848cc42fbd3a3032
  shared/build/consul:
    version: "v1.1.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/consul"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/consul/v1.1.0.tar.gz
        dest: consul-1.1.0.tar.gz
        checksum: 8e2539561eb07b2623d9828587e68f5ef46cee882227c7331ff26dddcdc0e9df
  shared/build/elasticsearch:
    version: "v6.4.0"
    required:
      BASE_IMAGE: "shared/nonredist/ubuntu1804"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/elasticsearch"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/elasticsearch/elasticsearch-v6.4.0.tar.gz
        dest: elasticsearch-6.4.0.tar.gz
        checksum: 33dcd95315833f8b2c87ec2db302c021ab7f0a47fdbe4cddb322748871679387
  shared/build/jq:
    version: "v1.5"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/jq"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/jq/jq-1.5.tar.gz
        dest: jq-1.5.tar.gz
        checksum: c4d2bfec6436341113419debf479d833692cc5cdab7eb0326b5a4d4fbe9f493c
  shared/build/dumb-init:
    version: "v1.2.1"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/dumb-init"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/dumb-init/dumb-init-1.2.1.tar.gz
        dest: dumb-init-1.2.1.tar.gz
        checksum: 56858088d9d6c911c227d196fcbfca06aff31fbe83e1519f9cabe5cf6f11b242
  shared/build/draft:
    version: "v0.13.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/draft"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/draft/draft-0.13.0.tar.gz
        dest: draft-0.13.0.tar.gz
        checksum: f9b2d7fcb5259506b60eb212af3be82f6e05f585548de2b0a1f891042e1ceb4a
  shared/build/metrics:
    version: "0.0.1"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../cli/experiment_metrics"
    push: False
  shared/utils/nginx:
    version: "v1.13.9"
    required:
      BASE_IMAGE: "shared/centos"
      NGINX_BUILD_IMAGE: "shared/build/nginx"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/utils/nginx"
    push: False
