---

proxy:
  http_proxy: http://proxy-mu.intel.com:911
  https_proxy: http://proxy-mu.intel.com:912
  no_proxy: os.mirror,.intel.com,127.0.0.1,localhost

images: "{{ shared_images | combine(local_images | default({})) }}"

shared_images:
  shared/centos:
    version: "7.5.1804"
    method: build
    push: False
    directory: "{{ playbook_dir }}/../../shared-containers/centos/core"
    required: {}
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/centos/centos-docker-0008.tar.xz
        dest: centos-docker.tar.xz
        checksum: d5759d1da5f8a1e70f29b7dacfe5458fb2edf86fc2679115e5a71eca463bfa42
  shared/centos/rpm-packer:
    version: "7.5.1804"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/rpm-packer"
    push: False
  shared/centos/docs:
    version: "7.5.1804"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../docs/end-user-docs/user-guide/HTML Files Source and Output/HTML-Output"
    dockerfile: "{{ playbook_dir }}/../../shared-containers/docs/Dockerfile"
    push: False
  shared/centos/build:
    version: "7.5.1804"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build"
    push: False
  shared/centos/python27:
    version: "2.7"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/python27"
    push: False
  shared/centos/python36:
    version: "3.6"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/python36"
    push: False
  shared/centos/build-go:
    version: "1.10.2"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/build-go"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/go/go1.10.2.linux-amd64.tar.gz
        dest: go1.10.2.linux-amd64.tar.gz
        checksum: 4b677d698c65370afa33757b6954ade60347aaca310ea92a63ed717d7cb0c2ff
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/godep/dep-linux-amd64
        dest: dep-linux-amd64
        checksum: 31144e465e52ffbc0035248a10ddea61a09bf28b00784fd3fdd9882c8cbb2315
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/glide/glide-v0.13.1-linux-amd64
        dest: glide-v0.13.1-linux-amd64
        checksum: b3e126a0034ab41005b51fc9542997b632f2802ee64ad0e3850c0353ba2867cf
  shared/centos/go-apiserver-builder:
    version: "v1.9-alpha.4"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/centos/go-apiserver-builder"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/apiserver-builder/apiserver-builder-v1.9-alpha.4-linux-amd64.tar.gz
        dest: apiserver-builder-v1.9-alpha.4-linux-amd64.tar.gz
        checksum: 6f82bb4d063b46a920f2952debd9ade19e712e7472d43e97ff09a2bf2f705ca6
  shared/build/kubernetes:
    version: "v1.10.11"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/kubernetes"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/kubernetes/v1.10.11.tar.gz
        dest: kubernetes.tar.gz
        checksum: 13c4554e945f4f7af42479c8a3ee656381a3e4272fd88d0b6db766aff21478f3
  shared/build/heapster:
    version: "v1.4.3"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/heapster"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/heapster/heapster-v1.4.3.tar.gz
        dest: heapster-v1.4.3.tar.gz
        checksum: 5a0e6fa74c8602d466338eb881af3bf4260940291e3eeb130e0ef9136c821f6c
  shared/build/tiller:
    version: "v2.11.0"
    required:
      BASE_IMAGE: "shared/centos"
      HELM_DATA_IMAGE: "shared/build/helm"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tiller"
    push: False
  shared/build/ingress:
    version: "0.14.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/authbind/authbind_2.1.2.tar.gz
        dest: authbind_2.1.2.tar.gz
        checksum: 7dfb138b6ceeab34d58906be2598812d6dcc83885e650f93414d4851027c968c
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/ingress"
    push: False
  shared/build/kubernetes-dashboard:
    version: "v1.8.3"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/kubernetes-dashboard"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/go/go1.10.2.linux-amd64.tar.gz
        dest: go1.10.2.linux-amd64.tar.gz
        checksum: 4b677d698c65370afa33757b6954ade60347aaca310ea92a63ed717d7cb0c2ff
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/kubernetes-dashboard/kubernetes-dashboard-v1.8.3.tar.gz
        dest: kubernetes-dashboard-v1.8.3.tar.gz
        checksum: 9096f86d4107a6d23f2cff5edd1acae2faf25719a343c319860fd6a7408f761d
  shared/build/kubernetes-addons:
    version: "v1.10.11"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/kubernetes-addons"
    push: False
  shared/build/docker:
    version: "v18.06.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/docker"
    push: False
    fetch_files:
      - src: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.68-1.el7.noarch.rpm
        dest: container-selinux-2.68-1.el7.noarch.rpm
        checksum: d2a6e716e12da75bca38a5c5d79cdb3863beb500389827121b6bca6df057aee9
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/docker/docker-ce-selinux-17.03.3.ce-1.el7.src.rpm
        dest: docker-ce-selinux-17.03.3.ce-1.el7.src.rpm
        checksum: 994c76793afde01ae467ead3aef7ad30369dbd9447b2752f62bb251e6f0a24ba
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/docker/docker-ce-18.06.0.ce-3.el7.centos.src.rpm
        dest: docker-ce-18.06.0.ce-3.el7.centos.src.rpm
        checksum: 2926f66a94f5b3bcd1e3feb0d7107f2fd2713cf3f412f84dcc8fe89120c43392
  shared/build/nginx:
    version: "v1.13.9"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/nginx"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/nginx/nginx-1.13.9-1.el7_4.ngx.src.rpm
        dest: nginx-1.13.9-1.el7_4.ngx.src.rpm
        checksum: 98d4329318dc9a681fa5e13cba5bc809bd2f7a97e38b36a1d07cb15a53b855ee
  shared/build/tensorflow/py2.7:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python27"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/2.7/build"
    push: False
  shared/build/tensorflow/py3.6:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/3.6/build"
    push: False
  shared/build/tensorflow/py2.7/1.9.0:
    version: "1.9.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/1.9.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/mkl/v1.9.0.tar.gz
        dest: tensorflow-v1.9.0.tar.gz
        checksum: ffc3151b06823d57b4a408261ba8efe53601563dfe93af0866751d4f6ca5068c
  shared/build/tensorflow/py3.6/1.9.0:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/1.9.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/mkl/v1.9.0.tar.gz
        dest: tensorflow-v1.9.0.tar.gz
        checksum: ffc3151b06823d57b4a408261ba8efe53601563dfe93af0866751d4f6ca5068c
  shared/build/tensorflow-serving/py2.7/1.9.0/haswell:
    version: "1.9.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow-serving/py2.7/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/haswell"
    push: False
  shared/build/tensorflow-serving/py3.6/1.9.0/skylake:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow-serving/py3.6/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/skylake"
    push: False
  shared/build/tensorflow/py2.7/1.9.0/haswell:
    version: "1.9.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/haswell"
    push: False
  shared/build/tensorflow/py3.6/1.9.0/haswell:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/haswell"
    push: False
  shared/build/tensorflow/py3.6/1.9.0/skylake:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow/skylake"
    push: False
  shared/build/tensorflow-serving/py2.7/1.9.0:
    version: "1.9.0-py2"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py2.7"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/1.9.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/tf-serving/1.9.0.tar.gz
        dest: tensorflow-serving-v1.9.0.tar.gz
        checksum: 860fc67fe6d385f721bf98b533d6cabb09162f8b1469e69af3c7e9f30dde0b92
  shared/build/tensorflow-serving/py3.6/1.9.0:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow/py3.6"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/1.9.0"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/tf-serving/1.9.0.tar.gz
        dest: tensorflow-serving-v1.9.0.tar.gz
        checksum: 860fc67fe6d385f721bf98b533d6cabb09162f8b1469e69af3c7e9f30dde0b92
  shared/build/tensorflow-serving/py3.6/1.9.0/haswell:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/build/tensorflow-serving/py3.6/1.9.0"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tensorflow-serving/haswell"
    push: False
  shared/run/tensorflow/py2.7:
    version: "py2"
    required:
      BASE_IMAGE: "shared/centos/python27"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/run"
    push: False
    args:
      PYTHON_VERSION: 2.7
  shared/run/tensorflow/py3.6:
    version: "py3"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/tf-base/run"
    push: False
    args:
      PYTHON_VERSION: 3.6
  shared/build/helm:
    version: "v2.11.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/helm"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/helm/v2.11.0.tar.gz
        dest: helm.tar.gz
        checksum: eee403cc1e05ab2eb1c6802eb7ecc4a5c544cb5971b7ee828c0b8d60fe061eb0
  shared/build/cni:
    version: "v0.7.1"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/cni"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/cni-plugins/v0.7.1.tar.gz
        dest: cni-plugins.tar.gz
        checksum: 6939d7fe0340879223cd3675b2cd1a13a41170781740cf5f856a4b06e379ffcb
  shared/build/consul:
    version: "v1.1.0"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/consul"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/consul/v1.1.0.tar.gz
        dest: consul-1.1.0.tar.gz
        checksum: 8e2539561eb07b2623d9828587e68f5ef46cee882227c7331ff26dddcdc0e9df
  shared/build/dumb-init:
    version: "v1.2.1"
    required:
      BASE_IMAGE: "shared/centos/build"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/build/dumb-init"
    push: False
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/dumb-init/dumb-init-1.2.1.tar.gz
        dest: dumb-init-1.2.1.tar.gz
        checksum: 56858088d9d6c911c227d196fcbfca06aff31fbe83e1519f9cabe5cf6f11b242
  shared/build/metrics:
    version: "0.0.1"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/cli/experiment_metrics"
    push: False
  shared/utils/nginx:
    version: "v1.13.9"
    required:
      BASE_IMAGE: "shared/centos"
      NGINX_BUILD_IMAGE: "shared/build/nginx"
    method: build
    directory: "{{ playbook_dir }}/../../shared-containers/utils/nginx"
    push: False
