---

export_images:
  - name: tiller
    value: "{{ image_local_url['dls4e/tiller'] }}"
  - name: tensorflow
    value: "{{ image_local_url['dls4e/tensorflow'] }}"
  - name: tensorboard
    value: "{{ image_local_url['dls4e/tensorflow'] }}"
  - name: tensorboard_service
    value: "{{ image_local_url['dls4e/tensorboard-service'] }}"

local_images:
  dls4e/centos:
    version: "7.5.1804"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/centos"
    required:
      BASE_IMAGE: "shared/centos"
    push: True
  dls4e/etcd:
    version: "3.1.10"
    image: "gcr.io/google-containers/etcd-amd64:3.1.10"
    method: "pull"
  dls4e/kubectl:
    version: "1.10.3"
    required:
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/kubectl"
  dls4e/gui:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos"
    method: build
    directory: "{{ playbook_dir }}/../../applications/dls-gui"
  dls4e/elasticsearch:
    version: "6.2.3"
    image: "quay.io/pires/docker-elasticsearch-kubernetes:6.2.3"
    method: pull
  dls4e/fluentd:
    version: "v0.12"
    image: "fluent/fluentd-kubernetes-daemonset:v0.12-debian-elasticsearch"
    method: pull
  dls4e/registry:
    version: "2.6.2"
    image: "registry:2.6.2"
    method: pull
  dls4e/samba:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
      JQ_DATA_IMAGE: "shared/build/jq"
      DUMBINIT_DATA_IMAGE: "shared/build/dumb-init"
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/samba"
  dls4e/tiller:
    version: "v2.9.1"
    image: "gcr.io/kubernetes-helm/tiller:v2.9.1"
    method: "pull"
  dls4e/redsocks:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/build"
    method: build
    fetch_files:
      - src: http://repository.toolbox.nervana.sclab.intel.com/DLS4E/downloads/redsocks/release-0.5.tar.gz
        dest: redsocks-0.5.tar.gz
        checksum: bbeb531d7f1986d7102f1bd6733dacce41d3f3ba7d604f1aab61c63e0ba2ee62
    directory: "{{ playbook_dir }}/../../dls4e-containers/redsocks"
  dls4e/experiment-service:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/go-apiserver-builder"
    method: build
    directory: "{{ playbook_dir }}/../../applications/experiment-service"
  dls4e/tensorflow/1.9.0py2/haswell/base:
    version: "1.9.0-py2"
    required:
      BASE_IMAGE: "shared/ubuntu"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/1.9.0py2/haswell"
    args:
      PYTHON_VERSION: 2
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tensorflow"
  dls4e/tensorflow/1.9.0py3/haswell/base:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/ubuntu"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/1.9.0py3/haswell"
    args:
      PYTHON_VERSION: 3
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tensorflow"
  dls4e/tensorflow/1.9.0py3/skylake/base:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "shared/ubuntu"
      TENSORFLOW_BUILD_IMAGE: "shared/build/tensorflow/1.9.0py3/skylake"
    args:
      PYTHON_VERSION: 3
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tensorflow"
  dls4e/tensorflow:
    version: "1.9.0-py3"
    required:
      BASE_IMAGE: "dls4e/tensorflow/1.9.0py3/haswell/base"
    method: build
    directory: "{{ playbook_dir }}/../../cli/experiment_metrics"
  dls4e/nginx:
    version: "1.14.0"
    method: pull
    image: "nginx:1.14.0"
  dls4e/postgres:
    version: "10.4"
    method: pull
    image: "postgres:10.4"
  dls4e/tf/operator:
    version: "v2"
    required:
      BASE_IMAGE: "shared/centos"
      BUILD_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tf-operator"
  dls4e/docker:
    version: "18.03"
    required:
      BASE_IMAGE: "dls4e/kubectl"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/docker"
  dls4e/ps-sidecar:
    version: "1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/ps-sidecar"
  dls4e/ingress:
    version: "0.14.0"
    image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.14.0"
    method: "pull"
  dls4e/defaultbackend:
    version: "1.4"
    image: "gcr.io/google-containers/defaultbackend-amd64:1.4"
    method: "pull"
  dls4e/dashboard:
    version: "v1.8.3"
    image: "k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3"
    method: "pull"
  dls4e/tensorboard-service:
    version: "v1.0.0"
    required:
      BASE_IMAGE: "shared/centos/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/tensorboard-service"

subcharts:
  dls4e-registry:
    registry:
      version: 2.6.2
      path: "{{ playbook_dir }}/../../dls4e-registry-charts/registry"
  dls4e:
    gui:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/gui"
      chart_values:
        image: "{{ image_local_url['dls4e/gui'] }}"
    admin-account:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/admin-account"
    experiments:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/experiments"
    configuration:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/configuration"
    commons:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/commons"
      chart_values:
        docker_image: "{{ image_local_url['dls4e/docker'] }}"
    docker-registry:
      version: 1.1.1
      path: "{{ playbook_dir }}/../../dls4e-charts/docker-registry"
      chart_values:
        image: "{{ image_local_url['dls4e/registry'] }}"
    elasticsearch:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/elasticsearch"
      chart_values:
        image: "{{ image_local_url['dls4e/elasticsearch'] }}"
        init_image: "{{ image_local_url['dls4e/centos'] }}"
    fluentd:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/fluentd"
      chart_values:
        image: "{{ image_local_url['dls4e/fluentd'] }}"
    samba:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/samba"
      chart_values:
        image: "{{ image_local_url['dls4e/samba'] }}"
    redsocks:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/redsocks"
      conditions: features.redsocks
      feature_enabled: False
      chart_values:
        image: "{{ image_local_url['dls4e/redsocks'] }}"
        Interfaces: cni0
    registry-nginx:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/registry-nginx"
      chart_values:
        image: "{{ image_local_url['dls4e/nginx'] }}"
    experiment-service:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/experiment-service"
      chart_values:
        image: "{{ image_local_url['dls4e/postgres'] }}"
        service_image: "{{ image_local_url['dls4e/experiment-service'] }}"
        etcd_image: "{{ image_local_url['dls4e/etcd'] }}"
    tf:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../dls4e-charts/tf"
      chart_values:
        image: "{{ image_local_url['dls4e/tf/operator'] }}"
        tfimage: "{{ image_local_url['dls4e/tensorflow'] }}"
    ingress:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/ingress"
      chart_values:
        image: "{{ image_local_url['dls4e/ingress'] }}"
        defaultbackend_image: "{{ image_local_url['dls4e/defaultbackend'] }}"
    dashboard:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../dls4e-charts/dashboard"
      chart_values:
        image: "{{ image_local_url['dls4e/dashboard'] }}"
