---

images:
  dls4e/centos:
    version: "7.4.1708"
    image: "centos:7.4.1708"
    method: "pull"
    push: False
  dls4e/build:
    version: "7.4.1708"
    required:
      BASE_IMAGE: "dls4e/centos"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/build"
    push: False
  dls4e/build-go:
    version: "1.10.2"
    required:
      BASE_IMAGE: "dls4e/build"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/build-go"
    push: False
  dls4e/go-apiserver-builder:
    version: "v1.9-alpha.4"
    required:
      BASE_IMAGE: "dls4e/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/go-apiserver-builder"
    push: False
  dls4e/etcd:
    version: "3.1.10"
    image: "gcr.io/google-containers/etcd-amd64:3.1.10"
    method: "pull"
  dls4e/kubectl:
    version: "1.10.0"
    required:
      BASE_IMAGE: "dls4e/centos"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/kubectl"
  dls4e/gui:
    version: "1.0.0"
    required:
      BASE_IMAGE: "dls4e/centos"
    method: build
    directory: "{{ playbook_dir }}/../../applications/dls-gui"
  dls4e/elasticsearch:
    version: "5.6.9"
    image: "elasticsearch:5.6.9"
    method: pull
  dls4e/fluentd:
    version: "v0.12"
    image: "fluent/fluentd-kubernetes-daemonset:v0.12-debian-elasticsearch"
    method: pull
  dls4e/registry:
    version: "2.6.2"
    image: "registry:2.6.2"
    method: pull
  dls4e/samba:
    version: "1.0.0"
    required:
      BASE_IMAGE: "dls4e/python36"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/samba"
  dls4e/tiller:
    version: "v2.9.1"
    image: "gcr.io/kubernetes-helm/tiller:v2.9.1"
    method: "pull"
  dls4e/redsocks:
    version: "1.0.0"
    required:
      BASE_IMAGE: "dls4e/centos"
      BUILD_IMAGE: "dls4e/build"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/redsocks"
  dls4e/experiment-service:
    version: "1.0.0"
    required:
      BASE_IMAGE: "dls4e/centos"
      BUILD_IMAGE: "dls4e/go-apiserver-builder"
    method: build
    directory: "{{ playbook_dir }}/../../applications/experiment-service"
  dls4e/tensorflow:
    version: "1.8.0-py3"
    method: pull
    image: "tensorflow/tensorflow:1.8.0-py3"
  dls4e/tensorboard:
    version: "1.8.0-py3"
    method: pull
    image: "tensorflow/tensorflow:1.8.0-py3"
  dls4e/nginx:
    version: "1.14.0"
    method: pull
    image: "nginx:1.14.0"
  dls4e/postgres:
    version: "10.4"
    method: pull
    image: "postgres:10.4"
  dls4e/tf/operator:
    version: "v2"
    required:
      BASE_IMAGE: "dls4e/centos"
      BUILD_IMAGE: "dls4e/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/tf-operator"
  dls4e/python36:
    version: "3.6"
    required:
      BASE_IMAGE: "dls4e/centos"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/python36"
    push: False
  dls4e/docker:
    version: "18.03"
    required:
      BASE_IMAGE: "dls4e/kubectl"
    method: build
    directory: "{{ playbook_dir }}/../../dls4e-containers/docker"
  dls4e/ps-sidecar:
    version: "1.0.0"
    required:
      BASE_IMAGE: "dls4e/python36"
    method: build
    directory: "{{ playbook_dir }}/../../applications/ps-sidecar"
  dls4e/ingress:
    version: "0.14.0"
    image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.14.0"
    method: "pull"
  dls4e/defaultbackend:
    version: "1.4"
    image: "gcr.io/google-containers/defaultbackend-amd64:1.4"
    method: "pull"
  dls4e/dashboard:
    version: "v1.8.3"
    image: "k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3"
    method: "pull"

subcharts:
  dls4e-registry:
    registry:
      version: 2.6.2
      path: "{{ playbook_dir }}/../../dls4e-registry-charts/registry"
  dls4e:
    dls-gui:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/dls-gui"
      chart_values:
        image: dls4e/gui:1.0.0
    dls-experiments:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/dls-experiments"
    dls-configuration:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/dls-configuration"
    dls-commons:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/dls-commons"
      chart_values:
        docker_image: dls4e/docker:18.03
    docker-registry:
      version: 1.1.1
      path: "{{ playbook_dir }}/../../dls4e-charts/docker-registry"
      chart_values:
        image: dls4e/registry:2.6.2
    elasticsearch:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/elasticsearch"
      chart_values:
        image: dls4e/elasticsearch:5.6.9
    fluentd:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../dls4e-charts/fluentd"
      chart_values:
        image: dls4e/fluentd:v0.12
    samba:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/samba"
      chart_values:
        image: dls4e/samba:1.0.0
    redsocks:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/redsocks"
      conditions: features.redsocks
      feature_enabled: False
      chart_values:
        image: dls4e/redsocks:1.0.0
        Interfaces: cni0
    registry-nginx:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/registry-nginx"
      chart_values:
        image: dls4e/nginx:1.14.0
    experiment-service:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/experiment-service"
      chart_values:
        image: dls4e/postgres:10.4
        service_image: dls4e/experiment-service:1.0.0
        etcd_image: dls4e/etcd:3.1.10
    tf:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../dls4e-charts/tf"
      chart_values:
        image: dls4e/tf/operator:v2
        tfimage: dls4e/tensorflow:1.8.0-py3
    dls-ingress:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../dls4e-charts/dls-ingress"
      chart_values:
        image: dls4e/ingress:0.14.0
        defaultbackend_image: dls4e/defaultbackend:1.4
    dashboard:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../dls4e-charts/dashboard"
      chart_values:
        image: dls4e/dashboard:v1.8.3
