---

local_images:
  core/flannel:
    version: "v0.9.1"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/flannel"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/flannel"
  core/kube-proxy:
    version: "v1.10.6"
    image: "gcr.io/google-containers/kube-proxy-amd64:v1.10.6"
    method: "pull"
  core/pause:
    version: "3.1"
    image: "gcr.io/google-containers/pause-amd64:3.1"
    method: "pull"
  core/tiller:
    version: "v2.9.1"
    image: "gcr.io/kubernetes-helm/tiller:v2.9.1"
    method: "pull"
  core/addon-resizer:
    version: "v1.7"
    image: "k8s.gcr.io/addon-resizer:1.7"
    method: "pull"
  core/heapster:
    version: "v1.4.2"
    image: "k8s.gcr.io/heapster-amd64:v1.4.2"
    method: "pull"
  core/defaultbackend:
    version: "1.4"
    image: "gcr.io/google-containers/defaultbackend-amd64:1.4"
    method: "pull"
  core/ingress:
    version: "0.14.0"
    image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.14.0"
    method: "pull"
  core/kube-dns:
    version: "1.14.8"
    image: "gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.8"
    method: "pull"
  core/dnsmasq-nanny:
    version: "1.14.8"
    image: "gcr.io/google-containers/k8s-dns-dnsmasq-nanny-amd64:1.14.8"
    method: "pull"
  core/dns-sidecar:
    version: "1.14.8"
    image: "gcr.io/google-containers/k8s-dns-sidecar-amd64:1.14.8"
    method: "pull"
  core/etcd:
    version: "3.3.9"
    required:
      BASE_IMAGE: "shared/centos"
      DATA_IMAGE: "shared/build/etcd"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/etcd"
  core/dashboard:
    version: "v1.8.3"
    image: "k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3"
    method: "pull"
  core/registry:
    version: "v2"
    image: "registry:2"
    required:
      BASE_IMAGE: "shared/centos/build-go"
    method: build
    directory: "{{ playbook_dir }}/../../platform-containers/registry"

chart_values:
  features: {}

subcharts:
  dls4e-platform:
    priority-classes:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../platform-charts/priority-classes"
    dashboard:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/dashboard"
      chart_values:
        image: "{{ image_local_url['core/dashboard'] }}"
    flannel:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/flannel"
      chart_values:
        image: "{{ image_local_url['core/flannel'] }}"
    heapster:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/heapster"
      chart_values:
        image: "{{ image_local_url['core/heapster'] }}"
        nanny_image: "{{ image_local_url['core/addon-resizer'] }}"
    samba-forward:
      version: 0.0.1
      path: "{{ playbook_dir }}/../../platform-charts/samba-forward"
    admin:
      version: 1.0.0
      path: "{{ playbook_dir }}/../../platform-charts/admin"
    skydns:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/skydns"
      chart_values:
        kubedns_image: "{{ image_local_url['core/kube-dns'] }}"
        nanny_image: "{{ image_local_url['core/dnsmasq-nanny'] }}"
        sidecar_image: "{{ image_local_url['core/dns-sidecar'] }}"
    ingress:
      version: 0.1.0
      path: "{{ playbook_dir }}/../../platform-charts/ingress"
      chart_values:
        ingress_image: "{{ image_local_url['core/ingress'] }}"
        defaultbackend_image: "{{ image_local_url['core/defaultbackend'] }}"
