---

common_required:
  - iptables
  - libcgroup
  - libcgroup-tools
  - libcgroup-devel
  - selinux-policy >= 3.13.1-23
  - libseccomp-devel
  - libtool-ltdl-devel
  - policycoreutils-python
  - selinux-policy-targeted >= 3.13.1-102
  - selinux-policy-base >= 3.13.1-102
  - libffi-devel
  - byacc
  - gcc
  - gcc-c++
  - openssl-devel
  - openssl
  - vim
  - git
  - ebtables
  - byacc
  - cifs-utils
  - ebtables
  - ethtool
  - gcc
  - gcc-c++
  - git
  - iproute
  - iptables
  - iptables >= 1.4.21
  - libcgroup
  - libcgroup-devel
  - libcgroup-tools
  - libffi-devel
  - libseccomp-devel
  - libtool-ltdl-devel
  - make
  - nfs-utils
  - openssh
  - openssh-clients
  - openssl
  - openssl-devel
  - policycoreutils-python
  - python
  - python-backports
  - python-backports-ssl_match_hostname
  - python-devel
  - python-ipaddress
  - python-setuptools
  - rsync
  - selinux-policy >= 3.13.1-23
  - selinux-policy-base >= 3.13.1-102
  - selinux-policy-targeted >= 3.13.1-102
  - socat
  - systemd-libs
  - util-linux
  - vim
  - wget

local_images:
  rpm/python:
    version: "2.7"
    required:
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/python"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
    fetch_files:
      - src: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python2-pip-8.1.2-6.el7.noarch.rpm
        dest: python2-pip-8.1.2-6.el7.noarch.rpm
        checksum: d99bbd6fd197597da392019f62cb982113cfa6d359e916abc3844a138d807377
  rpm/docker:
    version: "18.03.1-ce"
    required:
      BASE_IMAGE: "shared/centos/rpm-packer"
      DATA_IMAGE: "shared/build/docker"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/docker"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
    fetch_files:
      - src: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/pigz-2.3.4-1.el7.x86_64.rpm
        dest: pigz-2.3.4-1.el7.centos.x86_64.rpm
        checksum: 107362ff688868473eeb86c8c62d362e0ed576e123b44d135cf96f2af11a05c0
      - src: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.68-1.el7.noarch.rpm
        dest: container-selinux-2.68-1.el7.noarch.rpm
        checksum: d2a6e716e12da75bca38a5c5d79cdb3863beb500389827121b6bca6df057aee9
  rpm/docker-distribution:
    version: "2.6.2"
    required:
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/docker-distribution"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
    fetch_files:
      - src: http://mirror.centos.org/centos/7/extras/x86_64/Packages/docker-distribution-2.6.2-2.git48294d9.el7.x86_64.rpm
        dest: docker-distribution-2.6.2-2.git48294d9.el7.x86_64.rpm
        checksum: 52b2c48b9bb4d0d5357057127799e4d71129fe8997dd0f770a9fe68ee7f3eff0
  rpm/cni:
    version: "v0.7.1"
    required:
      CNI_DATA_IMAGE: "shared/build/cni"
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/cni/prepare"
    push: False
  rpm/cni/rpm:
    version: "v0.7.1"
    required:
      BASE_IMAGE: "rpm/cni"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/cni/rpm"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/helm:
    version: "v2.11.0"
    required:
      HELM_DATA_IMAGE: "shared/build/helm"
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/helm/prepare"
    push: False
  rpm/helm/rpm/client:
    version: "v2.11.0"
    required:
      BASE_IMAGE: "rpm/helm"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/helm/rpm/client"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/kubernetes:
    version: "v1.10.11"
    required:
      KUBERNETES_DATA_IMAGE: "shared/build/kubernetes"
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/kubernetes/prepare"
    push: False
  rpm/kubernetes/rpm/server:
    version: "v1.10.3"
    required:
      BASE_IMAGE: "rpm/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/kubernetes/rpm/server"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/kubernetes/rpm/worker:
    version: "v1.10.3"
    required:
      BASE_IMAGE: "rpm/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/kubernetes/rpm/worker"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/kubernetes/rpm/client:
    version: "v1.10.3"
    required:
      BASE_IMAGE: "rpm/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/kubernetes/rpm/client"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/kubernetes/rpm/all:
    version: "v1.10.3"
    required:
      BASE_IMAGE: "rpm/kubernetes"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/kubernetes/rpm/all"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/nginx/rpm:
    version: "1.13.9"
    required:
      NGINX_BUILD_IMAGE: "shared/build/nginx"
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/nginx"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
  rpm/consul:
    version: "1.0.0"
    required:
      CONSUL_DATA_IMAGE: "shared/build/consul"
      BASE_IMAGE: "shared/centos/rpm-packer"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/consul/prepare"
    push: False
  rpm/consul/rpm:
    version: "1.0.0"
    required:
      BASE_IMAGE: "rpm/consul"
    method: build
    directory: "{{ playbook_dir }}/../../rpm-containers/consul/rpm"
    push: False
    artifacts:
      - src: /out/*
        dest: rpms
