apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluentd
  labels:
    app: {{ .Release.Name }}-fluentd
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fluentd
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fluentd
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: {{ .Release.Name }}-fluentd-service-account
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "IfNotPresent"
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "{{ .Values.elaticsearch.host }}"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "{{ .Values.elaticsearch.port }}"
          - name:  FLUENTD_CONF
            value: custom-config/fluent.conf
          - name: FLUENT_ELASTICSEARCH_USER
            value: none
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: none
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /fluentd/etc/custom-config
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-fluentd-config
          items:
          - key: fluent.conf
            path: fluent.conf
