---

- name: Syncronize all docs files
  synchronize:
    src: "{{ docs_package }}/"
    dest: "{{ build_dir }}/"

- name: Create package
  shell: tar -cf {{ output }} -I pigz ./
  args:
    chdir: "{{ build_dir }}"
